version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: place
      MYSQL_DATABASE: place
      MYSQL_USER: place
      MYSQL_PASSWORD: place
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8888:8080
    depends_on:
      - database

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./../app:/var/www/project
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./../app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
